version: 2
plugins:
  tslint:
    config: tsconfig.json
    enabled: true
exclude_patterns:
  - "lib/"
  - "routines/"
  - "src/*.spec.ts"
  - "src/index.cc"
  - "dist/"
  - "examples/"
  - "benchmarks/"
  - "docs/"
